M48
; DRILL file KiCad 10.0.0 date 2026-04-12T03:08:23
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-12T03:08:23-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.660
%
G90
G05
T2
X117.5Y-28.665
T1
G00X124.79Y-28.665
M15
G01X125.21Y-28.665
M16
G05
M30
