name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-validator:
    name: "Hardware Validation (Fuzzer)"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator g++

    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: tools/lx32_validator

    - name: Run Automated Setup & Fuzzer
      run: |
        chmod +x tools/setup.sh
        ./tools/setup.sh
